name: auto update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # Verified via https://crontab.guru/ for 1,7,12,18 Beijing time (UTC+8)
  - cron: "0 17,23,4,10 * * *" 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Updated from v2 to v4 <button class="citation-flag" data-index="1"><button class="citation-flag" data-index="4"><button class="citation-flag" data-index="6">
      - uses: actions/checkout@v4
        
      # Updated from v2 to v4 <button class="citation-flag" data-index="4"><button class="citation-flag" data-index="6">
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Updated from v1 to v4 and fixed restore-keys indentation <button class="citation-flag" data-index="4"><button class="citation-flag" data-index="6">
      - uses: actions/cache@v4
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: Update tv-guide
        run: |
          pwd
          python get-epg.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions-bot@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff-index --quiet HEAD || git commit -m "🚀 update tv-guide at $(date '+%Y-%m-%d %H:%M:%S')"

      # Added to handle potential merge conflicts <button class="citation-flag" data-index="8">
      - name: Pull changes
        run: git pull --rebase

      # Updated from master to specific version <button class="citation-flag" data-index="5"><button class="citation-flag" data-index="7">
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
